name: messenger_test

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-190.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  country_picker: ^2.0.26

  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  meta: ^1.12.0

  auto_route: ^8.1.4

  rxdart: ^0.28.0
  equatable: ^2.0.5
  uuid: ^4.4.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  test: ^1.25.2
  bloc_test: ^9.1.7
#  mockito: ^5.4.4
  build_runner: ^2.4.11
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
